### ISSUE TITLE
Get-LatestOSSupported.sh v2.2.1 Lists Ventura as Preview

### ISSUE THREAD

**Issue by rougegoat** [MLBZ521/MacAdmin#21]
Real minor thing but now that Ventura has been released, this extension should be updated to clarify it's no longer in preview.  As far as I can tell, all that would be needed is to change the URL on line 16 to be 

https://www.apple.com/macos/ventura/

and also remove the asterisk from "Ventura*" throughout the script.  Most IT teams should be able to do that themselves, but I know some will refuse to use something while it's in "Preview".

**Comment by MLBZ521** [comment]
@rougegoat This has been discussed on the MacAdmins Slack.

The script has not been updated for full support of Ventura, because it cannot be.  Apple has yet to publish the full system requirements for Ventura (e.g. storage requirements and RAM requirements).

The link you mention is not the type of source documentation that I include for reference and that link will be deleted in the future.  If you notice, the reference [link](https://support.apple.com/en-us/HT212735) in the script for Monterey was deleted on Monday as well -- this is typical practice every year and I have to go and find another source to reference.

This link https://support.apple.com/en-us/HT213264 is the page typically that would be used, but this source does not contain the information required.

The `*` is there not because the OS is in "Preview", but because the script cannot accurately determine if a Mac has the required storage space for Ventura.  Apple typically does not publish this information until the OS has been released, but as previously mentioned, they have not yet done so.  As soon as they do though, I'll be happy to update the EA.

v2.2.1 was pushed to fix a bug that someone reported after they noticed the issue on certain devices.

**Comment by rougegoat** [comment]
Sorry, I don't have access to Slack through my organization so I haven't been able to follow any conversations there.

Your explanation makes perfect sense.

**Comment by MLBZ521** [comment]
@rougegoat No worries.

The MacAdmins Slack organization is free and open to everyone.  You're welcome to join us there.
