### ISSUE TITLE
Extension Attributes/jamf_ea_CrowdStrikeVersion.sh error bigsur

### ISSUE THREAD

**Issue by mani2care** [MLBZ521/MacAdmin#5]
Getting error in bigsur while sunning the script :

Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “status.bin” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Library/Application Support/CrowdStrike/Falcon/status.bin, NSUnderlyingError=0x7f980cc22740 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
sysctl: unknown oid 'cs.version'
<result>Not Running</result>

**Comment by MLBZ521** [comment]
@mani2care Sorry, I did not get a notification for this.

I've made an update (v1.3.1) to this [script](https://github.com/MLBZ521/MacAdmin/blob/master/Jamf%20Pro/Extension%20Attributes/jamf_ea_CrowdStrikeVersion.sh) since you submitted this issue, are you still seeing this error?

**Comment by MLBZ521** [comment]
Feel free to re-open this issue if you're still experiencing it.

**Comment by kkll39** [comment]
Hello,
I also got the errors:
Checking if Crowd Strike is installed...
Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “status.bin” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Library/Application Support/CrowdStrike/Falcon/status.bin, NSUnderlyingError=0x600003b850b0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
sysctl: unknown oid 'cs.version'
checkstrike.sh: line 27: /opt/ManagedFrameworks/EA_History.log: No such file or directory
<result>Not Running</result>
(base) 

Could you please have a look.

**Comment by MLBZ521** [comment]
@javaxxl I may need additional information to be able to assist on this.  I haven't seen this error before first hand.

Which version of the script are you running?
What versions of macOS are you experiencing this on?
What sensor versions are you experiencing this on?

I did just add an easier method to disable the log locally functionality in v2.10.0 (f2b3f20).  If you disable it, you will no longer see:
```
checkstrike.sh: line 27: /opt/ManagedFrameworks/EA_History.log: No such file or directory
```
